version: '2'
services:
  travis:
    build:
      dockerfile: .travis/Dockerfile
      context: .
    volumes:
      - ./:/kinetic/src/mas_common_robotics
    image: argenos/bitbots-travis:common
    command: ["bash", "-c", "cd /kinetic && catkin build -c --no-status"]
  common:
    build: .
    image: argenos/bitbots-common


# Build and run tests
# catkin run_tests
# catkin test
# catkin_test_results build/mas_domestic_robotics

# Lint
# catkin_lint --strict --ignore CRITICAL_VAR_APPEND,LINK_DIRECTORY src/mas_domestic_robotics

# Install
# catkin config --install
