zoom:
    position:
        init: 0
        min: 0  
        max: 31424
    speed:
        min: 0
        max: 7
    factor:    
        min: 1
        max: 30       # optical: 30, digital: 432
camera:
    resolution: P720_30     # supported resolutions: "P720_25", "P720_30", "P720_50", "P720_60", "P1080_25", "P1080_30"
    frame_id: rgb_camera
